project:
  type: book

book:
  title: "Pandas Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/pd-notes
  site-url: https://pd-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Basics"
      chapters:
      - "contents/01-datatypes.ipynb"
      - "contents/02-series.ipynb"
      - "contents/03-dataframe.ipynb"
    - part: "Data Manipulation"
      chapters: 
      - "contents/04-select-col.ipynb"
      - "contents/05-filter-row.ipynb"
      - "contents/06-transform.ipynb"
      - "contents/07-aggregation.ipynb"
      - "contents/08-sorting.ipynb"
      - "contents/09-pivot.ipynb"
      - "contents/10-join.ipynb"
    - part: "Advanced Operation"
      chapters: 
      - "contents/11-string-and-regex.ipynb"
    - part: "How To"
      chapters: 
      - "contents/howtos/bindrows.ipynb"
      - "contents/howtos/agg.ipynb"
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
     light: 
       - cosmo
       - brand
     dark:
       - darkly 


execute:
  freeze: auto