project:
  type: book

book:
  title: "Pandas Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/pd-notes
  site-url: https://pd-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Basics"
      chapters:
      - "contents/01-datatypes.ipynb"
      - "contents/02-series.ipynb"
      - "contents/03-dataframe.ipynb"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand


execute:
  freeze: auto